# Dependabot will run on day 5 of each month at 03:09 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "9 3 5 * *"
    open-pull-requests-limit: 15

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "9 3 5 * *"
    open-pull-requests-limit: 20
    versioning-strategy: "increase"
    ignore:
      - dependency-name: '@types/node'
        update-types:
          - 'version-update:semver-major'
