/*global systemDictionary:true */
'use strict';

systemDictionary = {
    "activate_server": {                             "en": "Activate Server",                                 "de": "Server aktivieren",                               "ru": "Activate Server",                                 "pt": "Ativar servidor",                                 "nl": "Server activeren",                                "fr": "Activer le serveur",                              "it": "Attiva Server",                                   "es": "Activar servidor",                                "pl": "Aktywuj serwer",                                  "zh-cn": "激活服务器"},
    "atHome": {                                      "en": "Name of home",                                    "de": "Ortsname für Zuhause",                            "ru": "Имя места для дома",                              "pt": "Nome da casa",                                    "nl": "Naam van huis",                                   "fr": "Nom de la maison",                                "it": "Nome di casa",                                    "es": "nombre de la casa",                               "pl": "Nazwa domu",                                      "zh-cn": "房屋名称"},
    "password": {                                    "en": "Password",                                        "de": "Passwort",                                        "ru": "Пароль",                                          "pt": "Senha",                                           "nl": "Wachtwoord",                                      "fr": "Mot de passe",                                    "it": "Parola d'ordine",                                 "es": "Clave",                                           "pl": "Hasło",                                           "zh-cn": "密码"},
    "port": {                                        "en": "Port",                                            "de": "Port",                                            "ru": "Порт",                                            "pt": "Porta",                                           "nl": "Haven",                                           "fr": "Port",                                            "it": "Porta",                                           "es": "Puerto",                                          "pl": "Port",                                            "zh-cn": "港口"},
    "ssl": {                                         "en": "Use SLL (https://)",                              "de": "SSL (https://) verwenden",                        "ru": "Использовать SSL(https://)",                      "pt": "Usar SSL (https://)",                             "nl": "Gebruik SLL (https://)",                          "fr": "Utiliser SLL (https://)",                         "it": "Usa SLL (https://)",                              "es": "Usar SLL (https://)",                             "pl": "Użyj SSL (https://)",                             "zh-cn": "使用 SLL (https://)"},
    "user": {                                        "en": "User",                                            "de": "Benutzer",                                        "ru": "Пользователь",                                    "pt": "Do utilizador",                                   "nl": "Gebruiker",                                       "fr": "Utilisateur",                                     "it": "Utente",                                          "es": "Usuario",                                         "pl": "Użytkownik",                                      "zh-cn": "用户"},
    "private_certificate": {                         "en": "Private certificate",                             "de": "Privates Zertifikat",                             "ru": "Private certificate",                             "pt": "Private certificate",                             "nl": "Private certificate",                             "fr": "Private certificate",                             "it": "Private certificate",                             "es": "Private certificate",                             "pl": "Private certificate",                             "zh-cn": "Private certificate"},
    "public_certificate": {                          "en": "Public certificate",                              "de": "Öffentliches Zertifikat",                         "ru": "Public certificate",                              "pt": "Public certificate",                              "nl": "Public certificate",                              "fr": "Public certificate",                              "it": "Public certificate",                              "es": "Public certificate",                              "pl": "Public certificate",                              "zh-cn": "Public certificate"},
};